apiVersion: v1
kind: Pod
metadata:
  labels:
    run: complex-pod
  name: complex-pod
spec:
  initContainers:
  - image: busybox:1.36.1
    name: setup
    command: ['sh', '-c', 'wget -O- google.com']
  containers:
  - image: nginx:1.25.1
    name: complex-pod
    ports:
    - containerPort: 80

