apiVersion: v1
kind: Pod
metadata:
  labels:
    run: data-exchange
  name: data-exchange
spec:
  volumes:
  - name: logs-data
    emptyDir: {}
  containers:
  - image: busybox:1.36.1
    name: main-app
    command: ['sh', '-c', 'counter=1; while true; do touch "/var/app/data/$counter-data.txt"; counter=$((counter+1)); sleep 10; done']
    volumeMounts:
    - name: logs-data
      mountPath: /var/app/data/
  - image: busybox:1.36.1
    name: sidecar
    command:  ['sh', '-c', 'while true; do ls -d /var/app/data/*-data.txt | wc -l; sleep 10; done']
    volumeMounts:
    - name: logs-data
      mountPath: /var/app/data/
