apiVersion: v1
kind: Pod
metadata:
  labels:
    run: webserver
  name: webserver
spec:
  containers:
  - image: nginx:1.25.1
    name: nginx
    volumeMounts:
    - name: logs-vol
      mountPath: /var/log/nginx
  - image: busybox:1.36.1
    name: sidecar
    command: ["sh", "-c", "while true; do if [ \"$(cat /var/log/nginx/error.log | grep 'error')\" != \"\" ]; then echo 'Error discovered!'; fi; sleep 10; done"]    
    volumeMounts:
    - name: logs-vol
      mountPath: /var/log/nginx
  volumes:
  - name: logs-vol
    emptyDir: {}
