apiVersion: v1
kind: Pod
metadata:
  labels:
    run: web-server
  name: web-server
spec:
  containers:
  - image: nginx:1.23.0
    name: web-server
    ports:
    - containerPort: 80
      name: web-server-port
    startupProbe:
      httpGet:
        path: /
        port: web-server-port
    readinessProbe:
      httpGet:
        path: /
        port: web-server-port
      initialDelaySeconds: 5
    livenessProbe:
      httpGet:
        path: /
        port: web-server-port
      initialDelaySeconds: 10
      periodSeconds: 30
