apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-server-blue
spec:
  replicas: 4
  selector:
    matchLabels:
      app: blue
  template:
    metadata:
      labels:
        app: blue
    spec:
      containers:
      - image: httpd:2.4.23-alpine
        name: httpd
        ports:
        - containerPort: 80
          protocol: TCP
