apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-server-fixed
spec:
  replicas: 4 
  selector:
    matchLabels:
      app: httpd
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: httpd 
    spec:
      containers:
      - image: httpd:2.4.23-alpine
        name: httpd
        ports:
        - containerPort: 80
          protocol: TCP
