apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-server-green
spec:
  replicas: 4
  selector:
    matchLabels:
      app: green
  template:
    metadata:
      labels:
        app: green
    spec:
      containers:
      - image: httpd:2.4.57-alpine
        name: httpd
        ports:
        - containerPort: 80
          protocol: TCP
