apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginx-pod
  name: nginx-pod
spec:
  volumes:
  - name: nginx-logs
    persistentVolumeClaim:
      claimName: logs-pvc
  containers:
  - image: nginx:1.25.1
    name: nginx-pod
    volumeMounts:
      - mountPath: "/var/log/nginx"
        name: nginx-logs
