apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: app-cache
  name: app-cache
spec:
  replicas: 4
  selector:
    matchLabels:
      app: app-cache
  strategy: {}
  template:
    metadata:
      labels:
        app: app-cache
    spec:
      containers:
      - image: memcached:1.6.8
        name: memcached
        resources:
          requests:
            cpu: 250m
            memory: 100Mi
          limits:
            cpu: 500m
            memory: 500Mi
