apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: v1
    tier: backend
  name: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: v1
  strategy: {}
  template:
    metadata:
      labels:
        app: v1
    spec:
      containers:
      - image: nginx:1.23.0
        name: nginx
        resources: {}
status: {}
